version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "052394459058"
    AWS_REGION: "us-east-1"
    ECR_REPO_NAME: "simple-springboot-app"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  
      - echo "Computing IMAGE_URI"
      - export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo "IMAGE_URI=$IMAGE_URI"

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - mvn clean package -DskipTests
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - docker push $IMAGE_URI
