version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "087189722990"
    AWS_REGION: "us-east-1"
    ECR_REPO_NAME: "simple-springboot-app"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo "IMAGE_URI=$IMAGE_URI"

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - mvn clean package -DskipTests
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - docker push $IMAGE_URI
